# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: CI
    jobs:
      - job: 'Build'
        pool:
          vmimage: ubuntu-latest
        steps: